/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | Guest : Role
  | Host : Role

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 2

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : W0)
    : Type where

structure W2
    (w0 : W0)
    (w1 : W1 w0)
    : Type where
  hidden_car_Host : Hidden Int
  W2_guard_domain_hidden_car_Host : domain_Enum_0 hidden_car_Host.reveal

structure W3
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    : Type where
  d_Guest : Int
  W3_guard_domain_d_Guest : domain_Enum_0 d_Guest

structure W4
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    : Type where
  goat_Host : Int
  W4_guard_domain_goat_Host : domain_Enum_0 goat_Host
  W4_guard_logic : (decide (goat_Host ≠ w3.d_Guest)) = true

structure W5
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    : Type where
  switch_Guest : Bool

structure W6
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3 w4)
    : Type where
  car_Host : Int
  W6_guard_domain_car_Host : domain_Enum_0 car_Host
  W6_guard_reveal_car_Host : car_Host = w2.hidden_car_Host.reveal
  W6_guard_logic : (decide (w4.goat_Host ≠ car_Host)) = true

structure ActionDag : Type where
  action0 : W0
  action1 : W1 action0
  action2 : W2 action0 action1
  action3 : W3 action0 action1 action2
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3 action4
  action6 : W6 action0 action1 action2 action3 action4 action5

end GameProtocol
