/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | Even : Role
  | Odd : Role

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2
    (w0 : W0)
    (w1 : W1)
    : Type where
  hidden_c_Odd : Hidden Bool

structure W3
    (w0 : W0)
    (w1 : W1)
    : Type where
  hidden_c_Even : Hidden Bool

structure W4
    (w0 : W0)
    (w1 : W1)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1)
    : Type where
  c_Odd : Bool
  W4_guard_reveal_c_Odd : c_Odd = w2.hidden_c_Odd.reveal

structure W5
    (w0 : W0)
    (w1 : W1)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1)
    : Type where
  c_Even : Bool
  W5_guard_reveal_c_Even : c_Even = w3.hidden_c_Even.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1
  action2 : W2 action0 action1
  action3 : W3 action0 action1
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3

end GameProtocol
