/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | A : Role
  | B : Role

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : W0)
    : Type where

structure W2
    (w0 : W0)
    (w1 : W1 w0)
    : Type where
  hidden_c_A : Hidden Bool

structure W3
    (w0 : W0)
    (w1 : W1 w0)
    : Type where
  hidden_c_B : Hidden Bool

structure W4
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1)
    : Type where
  c_A : Bool
  W4_guard_reveal_c_A : c_A = w2.hidden_c_A.reveal

structure W5
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1)
    : Type where
  c_B : Bool
  W5_guard_reveal_c_B : c_B = w3.hidden_c_B.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1 action0
  action2 : W2 action0 action1
  action3 : W3 action0 action1
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3

end GameProtocol
