/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | O : Role
  | X : Role

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 8

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : W0)
    : Type where

structure W2
    (w0 : W0)
    (w1 : W1 w0)
    : Type where
  c1_X : Int
  W2_guard_domain_c1_X : domain_Enum_0 c1_X

structure W3
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    : Type where
  c1_O : Int
  W3_guard_domain_c1_O : domain_Enum_0 c1_O
  W3_guard_logic : (decide (w2.c1_X ≠ c1_O)) = true

structure W4
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    : Type where
  c2_X : Int
  W4_guard_domain_c2_X : domain_Enum_0 c2_X
  W4_guard_logic : (((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ c2_X))) && (decide (w3.c1_O ≠ c2_X))) = true

structure W5
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    : Type where
  c2_O : Int
  W5_guard_domain_c2_O : domain_Enum_0 c2_O
  W5_guard_logic : ((((((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ w4.c2_X))) && (decide (w2.c1_X ≠ c2_O))) && (decide (w3.c1_O ≠ w4.c2_X))) && (decide (w3.c1_O ≠ c2_O))) && (decide (w4.c2_X ≠ c2_O))) = true

structure W6
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3 w4)
    : Type where
  c3_X : Int
  W6_guard_domain_c3_X : domain_Enum_0 c3_X
  W6_guard_logic : ((((((((((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ w4.c2_X))) && (decide (w2.c1_X ≠ w5.c2_O))) && (decide (w2.c1_X ≠ c3_X))) && (decide (w3.c1_O ≠ w4.c2_X))) && (decide (w3.c1_O ≠ w5.c2_O))) && (decide (w3.c1_O ≠ c3_X))) && (decide (w4.c2_X ≠ w5.c2_O))) && (decide (w4.c2_X ≠ c3_X))) && (decide (w5.c2_O ≠ c3_X))) = true

structure W7
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3 w4)
    (w6 : W6 w0 w1 w2 w3 w4 w5)
    : Type where
  c3_O : Int
  W7_guard_domain_c3_O : domain_Enum_0 c3_O
  W7_guard_logic : (((((((((((((((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ w4.c2_X))) && (decide (w2.c1_X ≠ w5.c2_O))) && (decide (w2.c1_X ≠ w6.c3_X))) && (decide (w2.c1_X ≠ c3_O))) && (decide (w3.c1_O ≠ w4.c2_X))) && (decide (w3.c1_O ≠ w5.c2_O))) && (decide (w3.c1_O ≠ w6.c3_X))) && (decide (w3.c1_O ≠ c3_O))) && (decide (w4.c2_X ≠ w5.c2_O))) && (decide (w4.c2_X ≠ w6.c3_X))) && (decide (w4.c2_X ≠ c3_O))) && (decide (w5.c2_O ≠ w6.c3_X))) && (decide (w5.c2_O ≠ c3_O))) && (decide (w6.c3_X ≠ c3_O))) = true

structure W8
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3 w4)
    (w6 : W6 w0 w1 w2 w3 w4 w5)
    (w7 : W7 w0 w1 w2 w3 w4 w5 w6)
    : Type where
  c4_X : Int
  W8_guard_domain_c4_X : domain_Enum_0 c4_X
  W8_guard_logic : (((((((((((((((((((((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ w4.c2_X))) && (decide (w2.c1_X ≠ w5.c2_O))) && (decide (w2.c1_X ≠ w6.c3_X))) && (decide (w2.c1_X ≠ w7.c3_O))) && (decide (w2.c1_X ≠ c4_X))) && (decide (w3.c1_O ≠ w4.c2_X))) && (decide (w3.c1_O ≠ w5.c2_O))) && (decide (w3.c1_O ≠ w6.c3_X))) && (decide (w3.c1_O ≠ w7.c3_O))) && (decide (w3.c1_O ≠ c4_X))) && (decide (w4.c2_X ≠ w5.c2_O))) && (decide (w4.c2_X ≠ w6.c3_X))) && (decide (w4.c2_X ≠ w7.c3_O))) && (decide (w4.c2_X ≠ c4_X))) && (decide (w5.c2_O ≠ w6.c3_X))) && (decide (w5.c2_O ≠ w7.c3_O))) && (decide (w5.c2_O ≠ c4_X))) && (decide (w6.c3_X ≠ w7.c3_O))) && (decide (w6.c3_X ≠ c4_X))) && (decide (w7.c3_O ≠ c4_X))) = true

structure W9
    (w0 : W0)
    (w1 : W1 w0)
    (w2 : W2 w0 w1)
    (w3 : W3 w0 w1 w2)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3 w4)
    (w6 : W6 w0 w1 w2 w3 w4 w5)
    (w7 : W7 w0 w1 w2 w3 w4 w5 w6)
    (w8 : W8 w0 w1 w2 w3 w4 w5 w6 w7)
    : Type where
  c4_O : Int
  W9_guard_domain_c4_O : domain_Enum_0 c4_O
  W9_guard_logic : ((((((((((((((((((((((((((((decide (w2.c1_X ≠ w3.c1_O)) && (decide (w2.c1_X ≠ w4.c2_X))) && (decide (w2.c1_X ≠ w5.c2_O))) && (decide (w2.c1_X ≠ w6.c3_X))) && (decide (w2.c1_X ≠ w7.c3_O))) && (decide (w2.c1_X ≠ w8.c4_X))) && (decide (w2.c1_X ≠ c4_O))) && (decide (w3.c1_O ≠ w4.c2_X))) && (decide (w3.c1_O ≠ w5.c2_O))) && (decide (w3.c1_O ≠ w6.c3_X))) && (decide (w3.c1_O ≠ w7.c3_O))) && (decide (w3.c1_O ≠ w8.c4_X))) && (decide (w3.c1_O ≠ c4_O))) && (decide (w4.c2_X ≠ w5.c2_O))) && (decide (w4.c2_X ≠ w6.c3_X))) && (decide (w4.c2_X ≠ w7.c3_O))) && (decide (w4.c2_X ≠ w8.c4_X))) && (decide (w4.c2_X ≠ c4_O))) && (decide (w5.c2_O ≠ w6.c3_X))) && (decide (w5.c2_O ≠ w7.c3_O))) && (decide (w5.c2_O ≠ w8.c4_X))) && (decide (w5.c2_O ≠ c4_O))) && (decide (w6.c3_X ≠ w7.c3_O))) && (decide (w6.c3_X ≠ w8.c4_X))) && (decide (w6.c3_X ≠ c4_O))) && (decide (w7.c3_O ≠ w8.c4_X))) && (decide (w7.c3_O ≠ c4_O))) && (decide (w8.c4_X ≠ c4_O))) = true

structure ActionDag : Type where
  action0 : W0
  action1 : W1 action0
  action2 : W2 action0 action1
  action3 : W3 action0 action1 action2
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3 action4
  action6 : W6 action0 action1 action2 action3 action4 action5
  action7 : W7 action0 action1 action2 action3 action4 action5 action6
  action8 : W8 action0 action1 action2 action3 action4 action5 action6 action7
  action9 : W9 action0 action1 action2 action3 action4 action5 action6 action7 action8

end GameProtocol
