/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | B1 : Role
  | B2 : Role
  | B3 : Role
  | Seller : Role

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := z = 0 ∨ z = 1 ∨ z = 2 ∨ z = 3 ∨ z = 4 ∨ z = 5 ∨ z = 6 ∨ z = 7 ∨ z = 8 ∨ z = 9 ∨ z = 10 ∨ z = 11 ∨ z = 12 ∨ z = 13 ∨ z = 14 ∨ z = 15 ∨ z = 16 ∨ z = 17 ∨ z = 18 ∨ z = 19 ∨ z = 20 ∨ z = 21 ∨ z = 22 ∨ z = 23 ∨ z = 24 ∨ z = 25 ∨ z = 26 ∨ z = 27 ∨ z = 28 ∨ z = 29 ∨ z = 30 ∨ z = 31 ∨ z = 32 ∨ z = 33 ∨ z = 34 ∨ z = 35 ∨ z = 36 ∨ z = 37 ∨ z = 38 ∨ z = 39 ∨ z = 40 ∨ z = 41 ∨ z = 42 ∨ z = 43 ∨ z = 44 ∨ z = 45 ∨ z = 46 ∨ z = 47 ∨ z = 48 ∨ z = 49 ∨ z = 50 ∨ z = 51 ∨ z = 52 ∨ z = 53 ∨ z = 54 ∨ z = 55 ∨ z = 56 ∨ z = 57 ∨ z = 58 ∨ z = 59 ∨ z = 60 ∨ z = 61 ∨ z = 62 ∨ z = 63 ∨ z = 64 ∨ z = 65 ∨ z = 66 ∨ z = 67 ∨ z = 68 ∨ z = 69 ∨ z = 70 ∨ z = 71 ∨ z = 72 ∨ z = 73 ∨ z = 74 ∨ z = 75 ∨ z = 76 ∨ z = 77 ∨ z = 78 ∨ z = 79 ∨ z = 80 ∨ z = 81 ∨ z = 82 ∨ z = 83 ∨ z = 84 ∨ z = 85 ∨ z = 86 ∨ z = 87 ∨ z = 88 ∨ z = 89 ∨ z = 90 ∨ z = 91 ∨ z = 92 ∨ z = 93 ∨ z = 94 ∨ z = 95 ∨ z = 96 ∨ z = 97 ∨ z = 98 ∨ z = 99 ∨ z = 100

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2 : Type where

structure W3 : Type where

structure W4
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B1 : Hidden Int
  W4_guard_domain_hidden_b_B1 : domain_Enum_0 hidden_b_B1.reveal

structure W5
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B2 : Hidden Int
  W5_guard_domain_hidden_b_B2 : domain_Enum_0 hidden_b_B2.reveal

structure W6
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B3 : Hidden Int
  W6_guard_domain_hidden_b_B3 : domain_Enum_0 hidden_b_B3.reveal

structure W7
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B1 : Int
  W7_guard_domain_b_B1 : domain_Enum_0 b_B1
  W7_guard_reveal_b_B1 : b_B1 = w4.hidden_b_B1.reveal

structure W8
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B2 : Int
  W8_guard_domain_b_B2 : domain_Enum_0 b_B2
  W8_guard_reveal_b_B2 : b_B2 = w5.hidden_b_B2.reveal

structure W9
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B3 : Int
  W9_guard_domain_b_B3 : domain_Enum_0 b_B3
  W9_guard_reveal_b_B3 : b_B3 = w6.hidden_b_B3.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1
  action2 : W2
  action3 : W3
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3
  action6 : W6 action0 action1 action2 action3
  action7 : W7 action0 action1 action2 action3 action4 action5 action6
  action8 : W8 action0 action1 action2 action3 action4 action5 action6
  action9 : W9 action0 action1 action2 action3 action4 action5 action6

end GameProtocol
