/- Generated by Vegas Lean Encoder - Policy: FAIR_PLAY -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | B1 : Role
  | B2 : Role
  | B3 : Role
  | Seller : Role

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := z = 0 ∨ z = 1 ∨ z = 2

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2 : Type where

structure W3 : Type where

structure W4
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B1 : Hidden Int
  W4_guard_domain_hidden_b_B1 : domain_Enum_0 hidden_b_B1.reveal

structure W5
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B2 : Hidden Int
  W5_guard_domain_hidden_b_B2 : domain_Enum_0 hidden_b_B2.reveal

structure W6
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    : Type where
  hidden_b_B3 : Hidden Int
  W6_guard_domain_hidden_b_B3 : domain_Enum_0 hidden_b_B3.reveal

structure W7
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B1 : Int
  W7_guard_domain_b_B1 : domain_Enum_0 b_B1
  W7_guard_reveal_b_B1 : b_B1 = w4.hidden_b_B1.reveal

structure W8
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B2 : Int
  W8_guard_domain_b_B2 : domain_Enum_0 b_B2
  W8_guard_reveal_b_B2 : b_B2 = w5.hidden_b_B2.reveal

structure W9
    (w0 : W0)
    (w1 : W1)
    (w2 : W2)
    (w3 : W3)
    (w4 : W4 w0 w1 w2 w3)
    (w5 : W5 w0 w1 w2 w3)
    (w6 : W6 w0 w1 w2 w3)
    : Type where
  b_B3 : Int
  W9_guard_domain_b_B3 : domain_Enum_0 b_B3
  W9_guard_reveal_b_B3 : b_B3 = w6.hidden_b_B3.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1
  action2 : W2
  action3 : W3
  action4 : W4 action0 action1 action2 action3
  action5 : W5 action0 action1 action2 action3
  action6 : W6 action0 action1 action2 action3
  action7 : W7 action0 action1 action2 action3 action4 action5 action6
  action8 : W8 action0 action1 action2 action3 action4 action5 action6
  action9 : W9 action0 action1 action2 action3 action4 action5 action6

end GameProtocol
