(* Generated by Vegas Coq Encoder - Policy: INDEPENDENT *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Guest | Host.

(* --- Liveness Primitives --- *)
Inductive Absence (r : Role) : Type := | Timeout : Absence r.

Inductive Maybe (r : Role) (A : Type) : Type :=
| Present : A -> Maybe r A
| Absent : Absence r -> Maybe r A.

Arguments Present {r} {A} _.
Arguments Absent {r} {A} _.

Definition IsPresent {r A} (u : Maybe r A) : Prop :=
  match u with Present _ => True | Absent _ => False end.

Definition getPresent {r A} (u : Maybe r A) : IsPresent u -> A :=
  match u with
  | Present a => fun _ => a
  | Absent _  => fun H => match H with end
  end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : Maybe r A) (f : A -> B) : option B :=
  match u with Present w => Some (f w) | Absent _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  (0%Z <= z)%Z /\ (z <= 2%Z)%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : Maybe Host (@W0))
 : Type := {
}.

Record W2 
  (w0 : Maybe Host (@W0))
  (w1 : Maybe Guest (@W1 w0))
 : Type := {
  hidden_car_Host : Hidden Z;

  W2_guard_domain : domain_Enum_0 (reveal hidden_car_Host);
}.

Record W3 
  (w0 : Maybe Host (@W0))
  (w1 : Maybe Guest (@W1 w0))
  (w2 : Maybe Host (@W2 w0 w1))
 : Type := {
  d_Guest : Z;

  W3_guard_domain : domain_Enum_0 d_Guest;
}.

Record W4 
  (w0 : Maybe Host (@W0))
  (w1 : Maybe Guest (@W1 w0))
  (w2 : Maybe Host (@W2 w0 w1))
  (w3 : Maybe Guest (@W3 w0 w1 w2))
 : Type := {
  goat_Host : Z;

  W4_guard_domain : domain_Enum_0 goat_Host;
  W4_guard_logic : lift2 (fun x y => negb (Z.eqb x y)) (Some goat_Host) (get_val w3 (fun w => w.(d_Guest))) = Some true;
}.

Record W5 
  (w0 : Maybe Host (@W0))
  (w1 : Maybe Guest (@W1 w0))
  (w2 : Maybe Host (@W2 w0 w1))
  (w3 : Maybe Guest (@W3 w0 w1 w2))
  (w4 : Maybe Host (@W4 w0 w1 w2 w3))
 : Type := {
  switch_Guest : bool;

}.

Record W6 
  (w0 : Maybe Host (@W0))
  (w1 : Maybe Guest (@W1 w0))
  (w2 : Maybe Host (@W2 w0 w1))
  (w3 : Maybe Guest (@W3 w0 w1 w2))
  (w4 : Maybe Host (@W4 w0 w1 w2 w3))
  (w5 : Maybe Guest (@W5 w0 w1 w2 w3 w4))
 : Type := {
  car_Host : Z;

  W6_guard_domain : domain_Enum_0 car_Host;
  W6_guard_w2_present : IsPresent w2;
  W6_guard_reveal : car_Host = reveal (getPresent w2 W6_guard_w2_present).(hidden_car_Host);
  W6_guard_logic : lift2 (fun x y => negb (Z.eqb x y)) (get_val w4 (fun w => w.(goat_Host))) (Some car_Host) = Some true;
}.

Record EventDag : Type := {
  event0 : Maybe Host (@W0);
  event1 : Maybe Guest (@W1 event0);
  event2 : Maybe Host (@W2 event0 event1);
  event3 : Maybe Guest (@W3 event0 event1 event2);
  event4 : Maybe Host (@W4 event0 event1 event2 event3);
  event5 : Maybe Guest (@W5 event0 event1 event2 event3 event4);
  event6 : Maybe Host (@W6 event0 event1 event2 event3 event4 event5);
}.

End GameProtocol.
