(* Generated by Vegas Coq Encoder - Policy: INDEPENDENT *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Even | Odd.

(* --- Liveness Primitives --- *)
Inductive Absence (r : Role) : Type := | Timeout : Absence r.

Inductive Maybe (r : Role) (A : Type) : Type :=
| Present : A -> Maybe r A
| Absent : Absence r -> Maybe r A.

Arguments Present {r} {A} _.
Arguments Absent {r} {A} _.

Definition IsPresent {r A} (u : Maybe r A) : Prop :=
  match u with Present _ => True | Absent _ => False end.

Definition getPresent {r A} (u : Maybe r A) : IsPresent u -> A :=
  match u with
  | Present a => fun _ => a
  | Absent _  => fun H => match H with end
  end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : Maybe r A) (f : A -> B) : option B :=
  match u with Present w => Some (f w) | Absent _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1  : Type := {
}.

Record W2 
  (w0 : Maybe Odd (@W0))
  (w1 : Maybe Even (@W1))
 : Type := {
  hidden_c_Odd : Hidden bool;

}.

Record W3 
  (w0 : Maybe Odd (@W0))
  (w1 : Maybe Even (@W1))
 : Type := {
  hidden_c_Even : Hidden bool;

}.

Record W4 
  (w0 : Maybe Odd (@W0))
  (w1 : Maybe Even (@W1))
  (w2 : Maybe Odd (@W2 w0 w1))
  (w3 : Maybe Even (@W3 w0 w1))
 : Type := {
  c_Odd : bool;

  W4_guard_w2_present : IsPresent w2;
  W4_guard_reveal : c_Odd = reveal (getPresent w2 W4_guard_w2_present).(hidden_c_Odd);
}.

Record W5 
  (w0 : Maybe Odd (@W0))
  (w1 : Maybe Even (@W1))
  (w2 : Maybe Odd (@W2 w0 w1))
  (w3 : Maybe Even (@W3 w0 w1))
 : Type := {
  c_Even : bool;

  W5_guard_w3_present : IsPresent w3;
  W5_guard_reveal : c_Even = reveal (getPresent w3 W5_guard_w3_present).(hidden_c_Even);
}.

Record EventDag : Type := {
  event0 : Maybe Odd (@W0);
  event1 : Maybe Even (@W1);
  event2 : Maybe Odd (@W2 event0 event1);
  event3 : Maybe Even (@W3 event0 event1);
  event4 : Maybe Odd (@W4 event0 event1 event2 event3);
  event5 : Maybe Even (@W5 event0 event1 event2 event3);
}.

End GameProtocol.
