(* Generated by Vegas Coq Encoder - Policy: INDEPENDENT *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | B1 | B2 | B3 | Seller.

(* --- Liveness Primitives --- *)
Inductive Absence (r : Role) : Type := | Timeout : Absence r.

Inductive Maybe (r : Role) (A : Type) : Type :=
| Present : A -> Maybe r A
| Absent : Absence r -> Maybe r A.

Arguments Present {r} {A} _.
Arguments Absent {r} {A} _.

Definition IsPresent {r A} (u : Maybe r A) : Prop :=
  match u with Present _ => True | Absent _ => False end.

Definition getPresent {r A} (u : Maybe r A) : IsPresent u -> A :=
  match u with
  | Present a => fun _ => a
  | Absent _  => fun H => match H with end
  end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : Maybe r A) (f : A -> B) : option B :=
  match u with Present w => Some (f w) | Absent _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  z = 0%Z \/ z = 1%Z \/ z = 2%Z \/ z = 3%Z \/ z = 4%Z \/ z = 5%Z \/ z = 6%Z \/ z = 7%Z \/ z = 8%Z \/ z = 9%Z \/ z = 10%Z \/ z = 11%Z \/ z = 12%Z \/ z = 13%Z \/ z = 14%Z \/ z = 15%Z \/ z = 16%Z \/ z = 17%Z \/ z = 18%Z \/ z = 19%Z \/ z = 20%Z \/ z = 21%Z \/ z = 22%Z \/ z = 23%Z \/ z = 24%Z \/ z = 25%Z \/ z = 26%Z \/ z = 27%Z \/ z = 28%Z \/ z = 29%Z \/ z = 30%Z \/ z = 31%Z \/ z = 32%Z \/ z = 33%Z \/ z = 34%Z \/ z = 35%Z \/ z = 36%Z \/ z = 37%Z \/ z = 38%Z \/ z = 39%Z \/ z = 40%Z \/ z = 41%Z \/ z = 42%Z \/ z = 43%Z \/ z = 44%Z \/ z = 45%Z \/ z = 46%Z \/ z = 47%Z \/ z = 48%Z \/ z = 49%Z \/ z = 50%Z \/ z = 51%Z \/ z = 52%Z \/ z = 53%Z \/ z = 54%Z \/ z = 55%Z \/ z = 56%Z \/ z = 57%Z \/ z = 58%Z \/ z = 59%Z \/ z = 60%Z \/ z = 61%Z \/ z = 62%Z \/ z = 63%Z \/ z = 64%Z \/ z = 65%Z \/ z = 66%Z \/ z = 67%Z \/ z = 68%Z \/ z = 69%Z \/ z = 70%Z \/ z = 71%Z \/ z = 72%Z \/ z = 73%Z \/ z = 74%Z \/ z = 75%Z \/ z = 76%Z \/ z = 77%Z \/ z = 78%Z \/ z = 79%Z \/ z = 80%Z \/ z = 81%Z \/ z = 82%Z \/ z = 83%Z \/ z = 84%Z \/ z = 85%Z \/ z = 86%Z \/ z = 87%Z \/ z = 88%Z \/ z = 89%Z \/ z = 90%Z \/ z = 91%Z \/ z = 92%Z \/ z = 93%Z \/ z = 94%Z \/ z = 95%Z \/ z = 96%Z \/ z = 97%Z \/ z = 98%Z \/ z = 99%Z \/ z = 100%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1  : Type := {
}.

Record W2  : Type := {
}.

Record W3  : Type := {
}.

Record W4 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
 : Type := {
  hidden_b_B1 : Hidden Z;

  W4_guard_domain : domain_Enum_0 (reveal hidden_b_B1);
}.

Record W5 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
  (w4 : Maybe B1 (@W4 w0 w1 w2 w3))
 : Type := {
  hidden_b_B2 : Hidden Z;

  W5_guard_domain : domain_Enum_0 (reveal hidden_b_B2);
}.

Record W6 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
  (w4 : Maybe B1 (@W4 w0 w1 w2 w3))
  (w5 : Maybe B2 (@W5 w0 w1 w2 w3 w4))
 : Type := {
  hidden_b_B3 : Hidden Z;

  W6_guard_domain : domain_Enum_0 (reveal hidden_b_B3);
}.

Record W7 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
  (w4 : Maybe B1 (@W4 w0 w1 w2 w3))
  (w5 : Maybe B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : Maybe B3 (@W6 w0 w1 w2 w3 w4 w5))
 : Type := {
  b_B1 : Z;

  W7_guard_domain : domain_Enum_0 b_B1;
  W7_guard_w4_present : IsPresent w4;
  W7_guard_reveal : b_B1 = reveal (getPresent w4 W7_guard_w4_present).(hidden_b_B1);
}.

Record W8 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
  (w4 : Maybe B1 (@W4 w0 w1 w2 w3))
  (w5 : Maybe B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : Maybe B3 (@W6 w0 w1 w2 w3 w4 w5))
  (w7 : Maybe B1 (@W7 w0 w1 w2 w3 w4 w5 w6))
 : Type := {
  b_B2 : Z;

  W8_guard_domain : domain_Enum_0 b_B2;
  W8_guard_w5_present : IsPresent w5;
  W8_guard_reveal : b_B2 = reveal (getPresent w5 W8_guard_w5_present).(hidden_b_B2);
}.

Record W9 
  (w0 : Maybe Seller (@W0))
  (w1 : Maybe B1 (@W1))
  (w2 : Maybe B2 (@W2))
  (w3 : Maybe B3 (@W3))
  (w4 : Maybe B1 (@W4 w0 w1 w2 w3))
  (w5 : Maybe B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : Maybe B3 (@W6 w0 w1 w2 w3 w4 w5))
  (w7 : Maybe B1 (@W7 w0 w1 w2 w3 w4 w5 w6))
  (w8 : Maybe B2 (@W8 w0 w1 w2 w3 w4 w5 w6 w7))
 : Type := {
  b_B3 : Z;

  W9_guard_domain : domain_Enum_0 b_B3;
  W9_guard_w6_present : IsPresent w6;
  W9_guard_reveal : b_B3 = reveal (getPresent w6 W9_guard_w6_present).(hidden_b_B3);
}.

Record EventDag : Type := {
  event0 : Maybe Seller (@W0);
  event1 : Maybe B1 (@W1);
  event2 : Maybe B2 (@W2);
  event3 : Maybe B3 (@W3);
  event4 : Maybe B1 (@W4 event0 event1 event2 event3);
  event5 : Maybe B2 (@W5 event0 event1 event2 event3 event4);
  event6 : Maybe B3 (@W6 event0 event1 event2 event3 event4 event5);
  event7 : Maybe B1 (@W7 event0 event1 event2 event3 event4 event5 event6);
  event8 : Maybe B2 (@W8 event0 event1 event2 event3 event4 event5 event6 event7);
  event9 : Maybe B3 (@W9 event0 event1 event2 event3 event4 event5 event6 event7 event8);
}.

End GameProtocol.
