/- Generated by Vegas Lean Encoder - Policy: INDEPENDENT -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | Guest : Role
  | Host : Role

/- Liveness Primitives -/
inductive Absence (r : Role) : Type where
  | timeout : Absence r

inductive Maybe (r : Role) (A : Type) : Type where
  | present : A → Maybe r A
  | absent : Absence r → Maybe r A

def Maybe.isPresent {r : Role} {A : Type} : Maybe r A → Prop
  | .present _ => True
  | .absent _ => False

def Maybe.getPresent {r : Role} {A : Type} (u : Maybe r A) (h : u.isPresent) : A :=
  match u with
  | .present a => a
  | .absent _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def Maybe.getVal {r : Role} {A B : Type} (u : Maybe r A) (f : A → B) : Option B :=
  match u with
  | .present w => some (f w)
  | .absent _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 2

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : Maybe Role.Host (W0))
    : Type where

structure W2
    (w0 : Maybe Role.Host (W0))
    (w1 : Maybe Role.Guest (W1 w0))
    : Type where
  hidden_car_Host : Hidden Int
  W2_guard_domain_hidden_car_Host : domain_Enum_0 hidden_car_Host.reveal

structure W3
    (w0 : Maybe Role.Host (W0))
    (w1 : Maybe Role.Guest (W1 w0))
    (w2 : Maybe Role.Host (W2 w0 w1))
    : Type where
  d_Guest : Int
  W3_guard_domain_d_Guest : domain_Enum_0 d_Guest

structure W4
    (w0 : Maybe Role.Host (W0))
    (w1 : Maybe Role.Guest (W1 w0))
    (w2 : Maybe Role.Host (W2 w0 w1))
    (w3 : Maybe Role.Guest (W3 w0 w1 w2))
    : Type where
  goat_Host : Int
  W4_guard_domain_goat_Host : domain_Enum_0 goat_Host
  W4_guard_logic : (lift2 (fun x y => decide (x ≠ y)) (some goat_Host) (w3.getVal (fun w => w.d_Guest))) = some true

structure W5
    (w0 : Maybe Role.Host (W0))
    (w1 : Maybe Role.Guest (W1 w0))
    (w2 : Maybe Role.Host (W2 w0 w1))
    (w3 : Maybe Role.Guest (W3 w0 w1 w2))
    (w4 : Maybe Role.Host (W4 w0 w1 w2 w3))
    : Type where
  switch_Guest : Bool

structure W6
    (w0 : Maybe Role.Host (W0))
    (w1 : Maybe Role.Guest (W1 w0))
    (w2 : Maybe Role.Host (W2 w0 w1))
    (w3 : Maybe Role.Guest (W3 w0 w1 w2))
    (w4 : Maybe Role.Host (W4 w0 w1 w2 w3))
    (w5 : Maybe Role.Guest (W5 w0 w1 w2 w3 w4))
    : Type where
  car_Host : Int
  W6_guard_domain_car_Host : domain_Enum_0 car_Host
  W6_guard_w2_present : w2.isPresent
  W6_guard_reveal_car_Host : car_Host = (w2.getPresent W6_guard_w2_present).hidden_car_Host.reveal
  W6_guard_logic : (lift2 (fun x y => decide (x ≠ y)) (w4.getVal (fun w => w.goat_Host)) (some car_Host)) = some true

structure EventDag : Type where
  event0 : Maybe Role.Host (W0)
  event1 : Maybe Role.Guest (W1 event0)
  event2 : Maybe Role.Host (W2 event0 event1)
  event3 : Maybe Role.Guest (W3 event0 event1 event2)
  event4 : Maybe Role.Host (W4 event0 event1 event2 event3)
  event5 : Maybe Role.Guest (W5 event0 event1 event2 event3 event4)
  event6 : Maybe Role.Host (W6 event0 event1 event2 event3 event4 event5)

end GameProtocol
