/- Generated by Vegas Lean Encoder - Policy: INDEPENDENT -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | Even : Role
  | Odd : Role

/- Liveness Primitives -/
inductive Absence (r : Role) : Type where
  | timeout : Absence r

inductive Maybe (r : Role) (A : Type) : Type where
  | present : A → Maybe r A
  | absent : Absence r → Maybe r A

def Maybe.isPresent {r : Role} {A : Type} : Maybe r A → Prop
  | .present _ => True
  | .absent _ => False

def Maybe.getPresent {r : Role} {A : Type} (u : Maybe r A) (h : u.isPresent) : A :=
  match u with
  | .present a => a
  | .absent _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def Maybe.getVal {r : Role} {A B : Type} (u : Maybe r A) (f : A → B) : Option B :=
  match u with
  | .present w => some (f w)
  | .absent _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2
    (w0 : Maybe Role.Odd (W0))
    (w1 : Maybe Role.Even (W1))
    : Type where
  hidden_c_Odd : Hidden Bool

structure W3
    (w0 : Maybe Role.Odd (W0))
    (w1 : Maybe Role.Even (W1))
    : Type where
  hidden_c_Even : Hidden Bool

structure W4
    (w0 : Maybe Role.Odd (W0))
    (w1 : Maybe Role.Even (W1))
    (w2 : Maybe Role.Odd (W2 w0 w1))
    (w3 : Maybe Role.Even (W3 w0 w1))
    : Type where
  c_Odd : Bool
  W4_guard_w2_present : w2.isPresent
  W4_guard_reveal_c_Odd : c_Odd = (w2.getPresent W4_guard_w2_present).hidden_c_Odd.reveal

structure W5
    (w0 : Maybe Role.Odd (W0))
    (w1 : Maybe Role.Even (W1))
    (w2 : Maybe Role.Odd (W2 w0 w1))
    (w3 : Maybe Role.Even (W3 w0 w1))
    : Type where
  c_Even : Bool
  W5_guard_w3_present : w3.isPresent
  W5_guard_reveal_c_Even : c_Even = (w3.getPresent W5_guard_w3_present).hidden_c_Even.reveal

structure EventDag : Type where
  event0 : Maybe Role.Odd (W0)
  event1 : Maybe Role.Even (W1)
  event2 : Maybe Role.Odd (W2 event0 event1)
  event3 : Maybe Role.Even (W3 event0 event1)
  event4 : Maybe Role.Odd (W4 event0 event1 event2 event3)
  event5 : Maybe Role.Even (W5 event0 event1 event2 event3)

end GameProtocol
