/- Generated by Vegas Lean Encoder - Policy: INDEPENDENT -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | B1 : Role
  | B2 : Role
  | B3 : Role
  | Seller : Role

/- Liveness Primitives -/
inductive Absence (r : Role) : Type where
  | timeout : Absence r

inductive Maybe (r : Role) (A : Type) : Type where
  | present : A → Maybe r A
  | absent : Absence r → Maybe r A

def Maybe.isPresent {r : Role} {A : Type} : Maybe r A → Prop
  | .present _ => True
  | .absent _ => False

def Maybe.getPresent {r : Role} {A : Type} (u : Maybe r A) (h : u.isPresent) : A :=
  match u with
  | .present a => a
  | .absent _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def Maybe.getVal {r : Role} {A B : Type} (u : Maybe r A) (f : A → B) : Option B :=
  match u with
  | .present w => some (f w)
  | .absent _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 2

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2 : Type where

structure W3 : Type where

structure W4
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    : Type where
  hidden_b_B1 : Hidden Int
  W4_guard_domain_hidden_b_B1 : domain_Enum_0 hidden_b_B1.reveal

structure W5
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    : Type where
  hidden_b_B2 : Hidden Int
  W5_guard_domain_hidden_b_B2 : domain_Enum_0 hidden_b_B2.reveal

structure W6
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    : Type where
  hidden_b_B3 : Hidden Int
  W6_guard_domain_hidden_b_B3 : domain_Enum_0 hidden_b_B3.reveal

structure W7
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    (w4 : Maybe Role.B1 (W4 w0 w1 w2 w3))
    (w5 : Maybe Role.B2 (W5 w0 w1 w2 w3))
    (w6 : Maybe Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B1 : Int
  W7_guard_domain_b_B1 : domain_Enum_0 b_B1
  W7_guard_w4_present : w4.isPresent
  W7_guard_reveal_b_B1 : b_B1 = (w4.getPresent W7_guard_w4_present).hidden_b_B1.reveal

structure W8
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    (w4 : Maybe Role.B1 (W4 w0 w1 w2 w3))
    (w5 : Maybe Role.B2 (W5 w0 w1 w2 w3))
    (w6 : Maybe Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B2 : Int
  W8_guard_domain_b_B2 : domain_Enum_0 b_B2
  W8_guard_w5_present : w5.isPresent
  W8_guard_reveal_b_B2 : b_B2 = (w5.getPresent W8_guard_w5_present).hidden_b_B2.reveal

structure W9
    (w0 : Maybe Role.Seller (W0))
    (w1 : Maybe Role.B1 (W1))
    (w2 : Maybe Role.B2 (W2))
    (w3 : Maybe Role.B3 (W3))
    (w4 : Maybe Role.B1 (W4 w0 w1 w2 w3))
    (w5 : Maybe Role.B2 (W5 w0 w1 w2 w3))
    (w6 : Maybe Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B3 : Int
  W9_guard_domain_b_B3 : domain_Enum_0 b_B3
  W9_guard_w6_present : w6.isPresent
  W9_guard_reveal_b_B3 : b_B3 = (w6.getPresent W9_guard_w6_present).hidden_b_B3.reveal

structure EventDag : Type where
  event0 : Maybe Role.Seller (W0)
  event1 : Maybe Role.B1 (W1)
  event2 : Maybe Role.B2 (W2)
  event3 : Maybe Role.B3 (W3)
  event4 : Maybe Role.B1 (W4 event0 event1 event2 event3)
  event5 : Maybe Role.B2 (W5 event0 event1 event2 event3)
  event6 : Maybe Role.B3 (W6 event0 event1 event2 event3)
  event7 : Maybe Role.B1 (W7 event0 event1 event2 event3 event4 event5 event6)
  event8 : Maybe Role.B2 (W8 event0 event1 event2 event3 event4 event5 event6)
  event9 : Maybe Role.B3 (W9 event0 event1 event2 event3 event4 event5 event6)

end GameProtocol
