(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Even | Odd.

Module GameProtocol.

Record W0  : Type := {
  hidden_c_Odd : Hidden bool;

}.

Record W1  : Type := {
  hidden_c_Even : Hidden bool;

}.

Record W2 
  (w0 : @W0)
  (w1 : @W1)
 : Type := {
  c_Odd : bool;

  W2_guard_reveal : c_Odd = reveal w0.(hidden_c_Odd);
}.

Record W3 
  (w0 : @W0)
  (w1 : @W1)
 : Type := {
  c_Even : bool;

  W3_guard_reveal : c_Even = reveal w1.(hidden_c_Even);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1;
  action2 : @W2 action0 action1;
  action3 : @W3 action0 action1;
}.

End GameProtocol.
