(* Generated by Vegas Coq Encoder - Policy: MONOTONIC *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Guest | Host.

(* --- Liveness Primitives --- *)
Inductive QuitW (r : Role) : Type := | Timeout : QuitW r.

Inductive UnlessQuit (r : Role) (A : Type) : Type :=
| Have : A -> UnlessQuit r A
| Quit : QuitW r -> UnlessQuit r A.

Arguments Have {r} {A} _.
Arguments Quit {r} {A} _.

Definition IsHave {r A} (u : UnlessQuit r A) : Prop :=
  match u with Have _ => True | Quit _ => False end.

Definition getHave {r A} (u : UnlessQuit r A) : IsHave u -> A :=
  match u with Have a => fun _ => a | Quit _ => fun H => match H with end end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : UnlessQuit r A) (f : A -> B) : option B :=
  match u with Have w => Some (f w) | Quit _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  (0%Z <= z)%Z /\ (z <= 2%Z)%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : UnlessQuit Host (@W0))
 : Type := {
}.

Record W2 
  (w0 : UnlessQuit Host (@W0))
  (w1 : UnlessQuit Guest (@W1 w0))
 : Type := {
  hidden_car_Host : Hidden Z;

  W2_guard_have_w0 : IsHave w0;
  W2_guard_domain : domain_Enum_0 (reveal hidden_car_Host);
}.

Record W3 
  (w0 : UnlessQuit Host (@W0))
  (w1 : UnlessQuit Guest (@W1 w0))
  (w2 : UnlessQuit Host (@W2 w0 w1))
 : Type := {
  d_Guest : Z;

  W3_guard_have_w1 : IsHave w1;
  W3_guard_domain : domain_Enum_0 d_Guest;
}.

Record W4 
  (w0 : UnlessQuit Host (@W0))
  (w1 : UnlessQuit Guest (@W1 w0))
  (w2 : UnlessQuit Host (@W2 w0 w1))
  (w3 : UnlessQuit Guest (@W3 w0 w1 w2))
 : Type := {
  goat_Host : Z;

  W4_guard_have_w0 : IsHave w0;
  W4_guard_have_w2 : IsHave w2;
  W4_guard_domain : domain_Enum_0 goat_Host;
  W4_guard_logic : lift2 (fun x y => negb (Z.eqb x y)) (Some goat_Host) (get_val w3 (fun w => w.(d_Guest))) = Some true;
}.

Record W5 
  (w0 : UnlessQuit Host (@W0))
  (w1 : UnlessQuit Guest (@W1 w0))
  (w2 : UnlessQuit Host (@W2 w0 w1))
  (w3 : UnlessQuit Guest (@W3 w0 w1 w2))
  (w4 : UnlessQuit Host (@W4 w0 w1 w2 w3))
 : Type := {
  switch_Guest : bool;

  W5_guard_have_w1 : IsHave w1;
  W5_guard_have_w3 : IsHave w3;
}.

Record W6 
  (w0 : UnlessQuit Host (@W0))
  (w1 : UnlessQuit Guest (@W1 w0))
  (w2 : UnlessQuit Host (@W2 w0 w1))
  (w3 : UnlessQuit Guest (@W3 w0 w1 w2))
  (w4 : UnlessQuit Host (@W4 w0 w1 w2 w3))
  (w5 : UnlessQuit Guest (@W5 w0 w1 w2 w3 w4))
 : Type := {
  car_Host : Z;

  W6_guard_have_w0 : IsHave w0;
  W6_guard_have_w2 : IsHave w2;
  W6_guard_have_w4 : IsHave w4;
  W6_guard_domain : domain_Enum_0 car_Host;
  W6_guard_reveal : car_Host = reveal (getHave w2 W6_guard_have_w2).(hidden_car_Host);
  W6_guard_logic : lift2 (fun x y => negb (Z.eqb x y)) (get_val w4 (fun w => w.(goat_Host))) (Some car_Host) = Some true;
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1 (@Have _ _ action0);
  action2 : @W2 (@Have _ _ action0) (@Have _ _ action1);
  action3 : @W3 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2);
  action4 : @W4 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3);
  action5 : @W5 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4);
  action6 : @W6 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4) (@Have _ _ action5);
}.

Record EventDag : Type := {
  event0 : UnlessQuit Host (@W0);
  event1 : UnlessQuit Guest (@W1 event0);
  event2 : UnlessQuit Host (@W2 event0 event1);
  event3 : UnlessQuit Guest (@W3 event0 event1 event2);
  event4 : UnlessQuit Host (@W4 event0 event1 event2 event3);
  event5 : UnlessQuit Guest (@W5 event0 event1 event2 event3 event4);
  event6 : UnlessQuit Host (@W6 event0 event1 event2 event3 event4 event5);
}.

End GameProtocol.
