(* Generated by Vegas Coq Encoder - Policy: MONOTONIC *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | A | B.

(* --- Liveness Primitives --- *)
Inductive QuitW (r : Role) : Type := | Timeout : QuitW r.

Inductive UnlessQuit (r : Role) (A : Type) : Type :=
| Have : A -> UnlessQuit r A
| Quit : QuitW r -> UnlessQuit r A.

Arguments Have {r} {A} _.
Arguments Quit {r} {A} _.

Definition IsHave {r A} (u : UnlessQuit r A) : Prop :=
  match u with Have _ => True | Quit _ => False end.

Definition getHave {r A} (u : UnlessQuit r A) : IsHave u -> A :=
  match u with Have a => fun _ => a | Quit _ => fun H => match H with end end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : UnlessQuit r A) (f : A -> B) : option B :=
  match u with Have w => Some (f w) | Quit _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : UnlessQuit A (@W0))
 : Type := {
}.

Record W2 
  (w0 : UnlessQuit A (@W0))
  (w1 : UnlessQuit B (@W1 w0))
 : Type := {
  hidden_c_A : Hidden bool;

  W2_guard_have_w0 : IsHave w0;
}.

Record W3 
  (w0 : UnlessQuit A (@W0))
  (w1 : UnlessQuit B (@W1 w0))
 : Type := {
  hidden_c_B : Hidden bool;

  W3_guard_have_w1 : IsHave w1;
}.

Record W4 
  (w0 : UnlessQuit A (@W0))
  (w1 : UnlessQuit B (@W1 w0))
  (w2 : UnlessQuit A (@W2 w0 w1))
  (w3 : UnlessQuit B (@W3 w0 w1))
 : Type := {
  c_A : bool;

  W4_guard_have_w0 : IsHave w0;
  W4_guard_have_w2 : IsHave w2;
  W4_guard_reveal : c_A = reveal (getHave w2 W4_guard_have_w2).(hidden_c_A);
}.

Record W5 
  (w0 : UnlessQuit A (@W0))
  (w1 : UnlessQuit B (@W1 w0))
  (w2 : UnlessQuit A (@W2 w0 w1))
  (w3 : UnlessQuit B (@W3 w0 w1))
 : Type := {
  c_B : bool;

  W5_guard_have_w1 : IsHave w1;
  W5_guard_have_w3 : IsHave w3;
  W5_guard_reveal : c_B = reveal (getHave w3 W5_guard_have_w3).(hidden_c_B);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1 (@Have _ _ action0);
  action2 : @W2 (@Have _ _ action0) (@Have _ _ action1);
  action3 : @W3 (@Have _ _ action0) (@Have _ _ action1);
  action4 : @W4 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3);
  action5 : @W5 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3);
}.

Record EventDag : Type := {
  event0 : UnlessQuit A (@W0);
  event1 : UnlessQuit B (@W1 event0);
  event2 : UnlessQuit A (@W2 event0 event1);
  event3 : UnlessQuit B (@W3 event0 event1);
  event4 : UnlessQuit A (@W4 event0 event1 event2 event3);
  event5 : UnlessQuit B (@W5 event0 event1 event2 event3);
}.

End GameProtocol.
