(* Generated by Vegas Coq Encoder - Policy: MONOTONIC *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | B1 | B2 | B3 | Seller.

(* --- Liveness Primitives --- *)
Inductive QuitW (r : Role) : Type := | Timeout : QuitW r.

Inductive UnlessQuit (r : Role) (A : Type) : Type :=
| Have : A -> UnlessQuit r A
| Quit : QuitW r -> UnlessQuit r A.

Arguments Have {r} {A} _.
Arguments Quit {r} {A} _.

Definition IsHave {r A} (u : UnlessQuit r A) : Prop :=
  match u with Have _ => True | Quit _ => False end.

Definition getHave {r A} (u : UnlessQuit r A) : IsHave u -> A :=
  match u with Have a => fun _ => a | Quit _ => fun H => match H with end end.

(* Helpers for accessing optional values and lifting operators *)
Definition get_val {r A B} (u : UnlessQuit r A) (f : A -> B) : option B :=
  match u with Have w => Some (f w) | Quit _ => None end.

Definition lift1 {A B} (f : A -> B) (x : option A) : option B :=
  match x with Some v => Some (f v) | None => None end.

Definition lift2 {A B C} (f : A -> B -> C) (x : option A) (y : option B) : option C :=
  match x, y with Some vx, Some vy => Some (f vx vy) | _, _ => None end.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  z = 0%Z \/ z = 1%Z \/ z = 2%Z \/ z = 3%Z \/ z = 4%Z \/ z = 5%Z \/ z = 6%Z \/ z = 7%Z \/ z = 8%Z \/ z = 9%Z \/ z = 10%Z \/ z = 11%Z \/ z = 12%Z \/ z = 13%Z \/ z = 14%Z \/ z = 15%Z \/ z = 16%Z \/ z = 17%Z \/ z = 18%Z \/ z = 19%Z \/ z = 20%Z \/ z = 21%Z \/ z = 22%Z \/ z = 23%Z \/ z = 24%Z \/ z = 25%Z \/ z = 26%Z \/ z = 27%Z \/ z = 28%Z \/ z = 29%Z \/ z = 30%Z \/ z = 31%Z \/ z = 32%Z \/ z = 33%Z \/ z = 34%Z \/ z = 35%Z \/ z = 36%Z \/ z = 37%Z \/ z = 38%Z \/ z = 39%Z \/ z = 40%Z \/ z = 41%Z \/ z = 42%Z \/ z = 43%Z \/ z = 44%Z \/ z = 45%Z \/ z = 46%Z \/ z = 47%Z \/ z = 48%Z \/ z = 49%Z \/ z = 50%Z \/ z = 51%Z \/ z = 52%Z \/ z = 53%Z \/ z = 54%Z \/ z = 55%Z \/ z = 56%Z \/ z = 57%Z \/ z = 58%Z \/ z = 59%Z \/ z = 60%Z \/ z = 61%Z \/ z = 62%Z \/ z = 63%Z \/ z = 64%Z \/ z = 65%Z \/ z = 66%Z \/ z = 67%Z \/ z = 68%Z \/ z = 69%Z \/ z = 70%Z \/ z = 71%Z \/ z = 72%Z \/ z = 73%Z \/ z = 74%Z \/ z = 75%Z \/ z = 76%Z \/ z = 77%Z \/ z = 78%Z \/ z = 79%Z \/ z = 80%Z \/ z = 81%Z \/ z = 82%Z \/ z = 83%Z \/ z = 84%Z \/ z = 85%Z \/ z = 86%Z \/ z = 87%Z \/ z = 88%Z \/ z = 89%Z \/ z = 90%Z \/ z = 91%Z \/ z = 92%Z \/ z = 93%Z \/ z = 94%Z \/ z = 95%Z \/ z = 96%Z \/ z = 97%Z \/ z = 98%Z \/ z = 99%Z \/ z = 100%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1  : Type := {
}.

Record W2  : Type := {
}.

Record W3  : Type := {
}.

Record W4 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
 : Type := {
  hidden_b_B1 : Hidden Z;

  W4_guard_have_w1 : IsHave w1;
  W4_guard_domain : domain_Enum_0 (reveal hidden_b_B1);
}.

Record W5 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
  (w4 : UnlessQuit B1 (@W4 w0 w1 w2 w3))
 : Type := {
  hidden_b_B2 : Hidden Z;

  W5_guard_have_w2 : IsHave w2;
  W5_guard_domain : domain_Enum_0 (reveal hidden_b_B2);
}.

Record W6 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
  (w4 : UnlessQuit B1 (@W4 w0 w1 w2 w3))
  (w5 : UnlessQuit B2 (@W5 w0 w1 w2 w3 w4))
 : Type := {
  hidden_b_B3 : Hidden Z;

  W6_guard_have_w3 : IsHave w3;
  W6_guard_domain : domain_Enum_0 (reveal hidden_b_B3);
}.

Record W7 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
  (w4 : UnlessQuit B1 (@W4 w0 w1 w2 w3))
  (w5 : UnlessQuit B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : UnlessQuit B3 (@W6 w0 w1 w2 w3 w4 w5))
 : Type := {
  b_B1 : Z;

  W7_guard_have_w1 : IsHave w1;
  W7_guard_have_w4 : IsHave w4;
  W7_guard_domain : domain_Enum_0 b_B1;
  W7_guard_reveal : b_B1 = reveal (getHave w4 W7_guard_have_w4).(hidden_b_B1);
}.

Record W8 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
  (w4 : UnlessQuit B1 (@W4 w0 w1 w2 w3))
  (w5 : UnlessQuit B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : UnlessQuit B3 (@W6 w0 w1 w2 w3 w4 w5))
  (w7 : UnlessQuit B1 (@W7 w0 w1 w2 w3 w4 w5 w6))
 : Type := {
  b_B2 : Z;

  W8_guard_have_w2 : IsHave w2;
  W8_guard_have_w5 : IsHave w5;
  W8_guard_domain : domain_Enum_0 b_B2;
  W8_guard_reveal : b_B2 = reveal (getHave w5 W8_guard_have_w5).(hidden_b_B2);
}.

Record W9 
  (w0 : UnlessQuit Seller (@W0))
  (w1 : UnlessQuit B1 (@W1))
  (w2 : UnlessQuit B2 (@W2))
  (w3 : UnlessQuit B3 (@W3))
  (w4 : UnlessQuit B1 (@W4 w0 w1 w2 w3))
  (w5 : UnlessQuit B2 (@W5 w0 w1 w2 w3 w4))
  (w6 : UnlessQuit B3 (@W6 w0 w1 w2 w3 w4 w5))
  (w7 : UnlessQuit B1 (@W7 w0 w1 w2 w3 w4 w5 w6))
  (w8 : UnlessQuit B2 (@W8 w0 w1 w2 w3 w4 w5 w6 w7))
 : Type := {
  b_B3 : Z;

  W9_guard_have_w3 : IsHave w3;
  W9_guard_have_w6 : IsHave w6;
  W9_guard_domain : domain_Enum_0 b_B3;
  W9_guard_reveal : b_B3 = reveal (getHave w6 W9_guard_have_w6).(hidden_b_B3);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1;
  action2 : @W2;
  action3 : @W3;
  action4 : @W4 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3);
  action5 : @W5 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4);
  action6 : @W6 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4) (@Have _ _ action5);
  action7 : @W7 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4) (@Have _ _ action5) (@Have _ _ action6);
  action8 : @W8 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4) (@Have _ _ action5) (@Have _ _ action6) (@Have _ _ action7);
  action9 : @W9 (@Have _ _ action0) (@Have _ _ action1) (@Have _ _ action2) (@Have _ _ action3) (@Have _ _ action4) (@Have _ _ action5) (@Have _ _ action6) (@Have _ _ action7) (@Have _ _ action8);
}.

Record EventDag : Type := {
  event0 : UnlessQuit Seller (@W0);
  event1 : UnlessQuit B1 (@W1);
  event2 : UnlessQuit B2 (@W2);
  event3 : UnlessQuit B3 (@W3);
  event4 : UnlessQuit B1 (@W4 event0 event1 event2 event3);
  event5 : UnlessQuit B2 (@W5 event0 event1 event2 event3 event4);
  event6 : UnlessQuit B3 (@W6 event0 event1 event2 event3 event4 event5);
  event7 : UnlessQuit B1 (@W7 event0 event1 event2 event3 event4 event5 event6);
  event8 : UnlessQuit B2 (@W8 event0 event1 event2 event3 event4 event5 event6 event7);
  event9 : UnlessQuit B3 (@W9 event0 event1 event2 event3 event4 event5 event6 event7 event8);
}.

End GameProtocol.
