/- Generated by Vegas Lean Encoder - Policy: MONOTONIC -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | Guest : Role
  | Host : Role

/- Liveness Primitives -/
inductive QuitW (r : Role) : Type where
  | timeout : QuitW r

inductive UnlessQuit (r : Role) (A : Type) : Type where
  | have : A → UnlessQuit r A
  | quit : QuitW r → UnlessQuit r A

def UnlessQuit.isHave {r : Role} {A : Type} : UnlessQuit r A → Prop
  | .have _ => True
  | .quit _ => False

def UnlessQuit.getHave {r : Role} {A : Type} (u : UnlessQuit r A) (h : u.isHave) : A :=
  match u with
  | .have a => a
  | .quit _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def UnlessQuit.getVal {r : Role} {A B : Type} (u : UnlessQuit r A) (f : A → B) : Option B :=
  match u with
  | .have w => some (f w)
  | .quit _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 2

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : UnlessQuit Role.Host (W0))
    : Type where

structure W2
    (w0 : UnlessQuit Role.Host (W0))
    (w1 : UnlessQuit Role.Guest (W1 w0))
    : Type where
  hidden_car_Host : Hidden Int
  W2_guard_have_w0 : w0.isHave
  W2_guard_domain_hidden_car_Host : domain_Enum_0 hidden_car_Host.reveal

structure W3
    (w0 : UnlessQuit Role.Host (W0))
    (w1 : UnlessQuit Role.Guest (W1 w0))
    (w2 : UnlessQuit Role.Host (W2 w0 w1))
    : Type where
  d_Guest : Int
  W3_guard_have_w1 : w1.isHave
  W3_guard_domain_d_Guest : domain_Enum_0 d_Guest

structure W4
    (w0 : UnlessQuit Role.Host (W0))
    (w1 : UnlessQuit Role.Guest (W1 w0))
    (w2 : UnlessQuit Role.Host (W2 w0 w1))
    (w3 : UnlessQuit Role.Guest (W3 w0 w1 w2))
    : Type where
  goat_Host : Int
  W4_guard_have_w0 : w0.isHave
  W4_guard_have_w2 : w2.isHave
  W4_guard_domain_goat_Host : domain_Enum_0 goat_Host
  W4_guard_logic : (lift2 (fun x y => decide (x ≠ y)) (some goat_Host) (w3.getVal (fun w => w.d_Guest))) = some true

structure W5
    (w0 : UnlessQuit Role.Host (W0))
    (w1 : UnlessQuit Role.Guest (W1 w0))
    (w2 : UnlessQuit Role.Host (W2 w0 w1))
    (w3 : UnlessQuit Role.Guest (W3 w0 w1 w2))
    (w4 : UnlessQuit Role.Host (W4 w0 w1 w2 w3))
    : Type where
  switch_Guest : Bool
  W5_guard_have_w1 : w1.isHave
  W5_guard_have_w3 : w3.isHave

structure W6
    (w0 : UnlessQuit Role.Host (W0))
    (w1 : UnlessQuit Role.Guest (W1 w0))
    (w2 : UnlessQuit Role.Host (W2 w0 w1))
    (w3 : UnlessQuit Role.Guest (W3 w0 w1 w2))
    (w4 : UnlessQuit Role.Host (W4 w0 w1 w2 w3))
    (w5 : UnlessQuit Role.Guest (W5 w0 w1 w2 w3 w4))
    : Type where
  car_Host : Int
  W6_guard_have_w0 : w0.isHave
  W6_guard_have_w2 : w2.isHave
  W6_guard_have_w4 : w4.isHave
  W6_guard_domain_car_Host : domain_Enum_0 car_Host
  W6_guard_reveal_car_Host : car_Host = (w2.getHave W6_guard_have_w2).hidden_car_Host.reveal
  W6_guard_logic : (lift2 (fun x y => decide (x ≠ y)) (w4.getVal (fun w => w.goat_Host)) (some car_Host)) = some true

structure ActionDag : Type where
  action0 : W0
  action1 : W1 (UnlessQuit.have action0)
  action2 : W2 (UnlessQuit.have action0) (UnlessQuit.have action1)
  action3 : W3 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2)
  action4 : W4 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)
  action5 : W5 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3) (UnlessQuit.have action4)
  action6 : W6 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3) (UnlessQuit.have action4) (UnlessQuit.have action5)

structure EventDag : Type where
  event0 : UnlessQuit Role.Host (W0)
  event1 : UnlessQuit Role.Guest (W1 event0)
  event2 : UnlessQuit Role.Host (W2 event0 event1)
  event3 : UnlessQuit Role.Guest (W3 event0 event1 event2)
  event4 : UnlessQuit Role.Host (W4 event0 event1 event2 event3)
  event5 : UnlessQuit Role.Guest (W5 event0 event1 event2 event3 event4)
  event6 : UnlessQuit Role.Host (W6 event0 event1 event2 event3 event4 event5)

end GameProtocol
