/- Generated by Vegas Lean Encoder - Policy: MONOTONIC -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | A : Role
  | B : Role

/- Liveness Primitives -/
inductive QuitW (r : Role) : Type where
  | timeout : QuitW r

inductive UnlessQuit (r : Role) (A : Type) : Type where
  | have : A → UnlessQuit r A
  | quit : QuitW r → UnlessQuit r A

def UnlessQuit.isHave {r : Role} {A : Type} : UnlessQuit r A → Prop
  | .have _ => True
  | .quit _ => False

def UnlessQuit.getHave {r : Role} {A : Type} (u : UnlessQuit r A) (h : u.isHave) : A :=
  match u with
  | .have a => a
  | .quit _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def UnlessQuit.getVal {r : Role} {A B : Type} (u : UnlessQuit r A) (f : A → B) : Option B :=
  match u with
  | .have w => some (f w)
  | .quit _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

namespace GameProtocol

structure W0 : Type where

structure W1
    (w0 : UnlessQuit Role.A (W0))
    : Type where

structure W2
    (w0 : UnlessQuit Role.A (W0))
    (w1 : UnlessQuit Role.B (W1 w0))
    : Type where
  hidden_c_A : Hidden Bool
  W2_guard_have_w0 : w0.isHave

structure W3
    (w0 : UnlessQuit Role.A (W0))
    (w1 : UnlessQuit Role.B (W1 w0))
    : Type where
  hidden_c_B : Hidden Bool
  W3_guard_have_w1 : w1.isHave

structure W4
    (w0 : UnlessQuit Role.A (W0))
    (w1 : UnlessQuit Role.B (W1 w0))
    (w2 : UnlessQuit Role.A (W2 w0 w1))
    (w3 : UnlessQuit Role.B (W3 w0 w1))
    : Type where
  c_A : Bool
  W4_guard_have_w0 : w0.isHave
  W4_guard_have_w2 : w2.isHave
  W4_guard_reveal_c_A : c_A = (w2.getHave W4_guard_have_w2).hidden_c_A.reveal

structure W5
    (w0 : UnlessQuit Role.A (W0))
    (w1 : UnlessQuit Role.B (W1 w0))
    (w2 : UnlessQuit Role.A (W2 w0 w1))
    (w3 : UnlessQuit Role.B (W3 w0 w1))
    : Type where
  c_B : Bool
  W5_guard_have_w1 : w1.isHave
  W5_guard_have_w3 : w3.isHave
  W5_guard_reveal_c_B : c_B = (w3.getHave W5_guard_have_w3).hidden_c_B.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1 (UnlessQuit.have action0)
  action2 : W2 (UnlessQuit.have action0) (UnlessQuit.have action1)
  action3 : W3 (UnlessQuit.have action0) (UnlessQuit.have action1)
  action4 : W4 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)
  action5 : W5 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)

structure EventDag : Type where
  event0 : UnlessQuit Role.A (W0)
  event1 : UnlessQuit Role.B (W1 event0)
  event2 : UnlessQuit Role.A (W2 event0 event1)
  event3 : UnlessQuit Role.B (W3 event0 event1)
  event4 : UnlessQuit Role.A (W4 event0 event1 event2 event3)
  event5 : UnlessQuit Role.B (W5 event0 event1 event2 event3)

end GameProtocol
