/- Generated by Vegas Lean Encoder - Policy: MONOTONIC -/

set_option autoImplicit false

/-- Hidden value with commitment semantics -/
structure Hidden (A : Type) where
  val : A

def Hidden.reveal {A : Type} (h : Hidden A) : A := h.val

/-- Game roles -/
inductive Role : Type where
  | B1 : Role
  | B2 : Role
  | B3 : Role
  | Seller : Role

/- Liveness Primitives -/
inductive QuitW (r : Role) : Type where
  | timeout : QuitW r

inductive UnlessQuit (r : Role) (A : Type) : Type where
  | have : A → UnlessQuit r A
  | quit : QuitW r → UnlessQuit r A

def UnlessQuit.isHave {r : Role} {A : Type} : UnlessQuit r A → Prop
  | .have _ => True
  | .quit _ => False

def UnlessQuit.getHave {r : Role} {A : Type} (u : UnlessQuit r A) (h : u.isHave) : A :=
  match u with
  | .have a => a
  | .quit _ => False.elim h

/-- Extract value from wrapper, returning Option -/
def UnlessQuit.getVal {r : Role} {A B : Type} (u : UnlessQuit r A) (f : A → B) : Option B :=
  match u with
  | .have w => some (f w)
  | .quit _ => none

/-- Lift unary function over Option -/
def lift1 {A B : Type} (f : A → B) : Option A → Option B
  | some v => some (f v)
  | none => none

/-- Lift binary function over Option -/
def lift2 {A B C : Type} (f : A → B → C) : Option A → Option B → Option C
  | some vx, some vy => some (f vx vy)
  | _, _ => none

/- Domain Constraints -/
def domain_Enum_0 (z : Int) : Prop := 0 ≤ z ∧ z ≤ 2

namespace GameProtocol

structure W0 : Type where

structure W1 : Type where

structure W2 : Type where

structure W3 : Type where

structure W4
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    : Type where
  hidden_b_B1 : Hidden Int
  W4_guard_have_w1 : w1.isHave
  W4_guard_domain_hidden_b_B1 : domain_Enum_0 hidden_b_B1.reveal

structure W5
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    : Type where
  hidden_b_B2 : Hidden Int
  W5_guard_have_w2 : w2.isHave
  W5_guard_domain_hidden_b_B2 : domain_Enum_0 hidden_b_B2.reveal

structure W6
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    : Type where
  hidden_b_B3 : Hidden Int
  W6_guard_have_w3 : w3.isHave
  W6_guard_domain_hidden_b_B3 : domain_Enum_0 hidden_b_B3.reveal

structure W7
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    (w4 : UnlessQuit Role.B1 (W4 w0 w1 w2 w3))
    (w5 : UnlessQuit Role.B2 (W5 w0 w1 w2 w3))
    (w6 : UnlessQuit Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B1 : Int
  W7_guard_have_w1 : w1.isHave
  W7_guard_have_w4 : w4.isHave
  W7_guard_domain_b_B1 : domain_Enum_0 b_B1
  W7_guard_reveal_b_B1 : b_B1 = (w4.getHave W7_guard_have_w4).hidden_b_B1.reveal

structure W8
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    (w4 : UnlessQuit Role.B1 (W4 w0 w1 w2 w3))
    (w5 : UnlessQuit Role.B2 (W5 w0 w1 w2 w3))
    (w6 : UnlessQuit Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B2 : Int
  W8_guard_have_w2 : w2.isHave
  W8_guard_have_w5 : w5.isHave
  W8_guard_domain_b_B2 : domain_Enum_0 b_B2
  W8_guard_reveal_b_B2 : b_B2 = (w5.getHave W8_guard_have_w5).hidden_b_B2.reveal

structure W9
    (w0 : UnlessQuit Role.Seller (W0))
    (w1 : UnlessQuit Role.B1 (W1))
    (w2 : UnlessQuit Role.B2 (W2))
    (w3 : UnlessQuit Role.B3 (W3))
    (w4 : UnlessQuit Role.B1 (W4 w0 w1 w2 w3))
    (w5 : UnlessQuit Role.B2 (W5 w0 w1 w2 w3))
    (w6 : UnlessQuit Role.B3 (W6 w0 w1 w2 w3))
    : Type where
  b_B3 : Int
  W9_guard_have_w3 : w3.isHave
  W9_guard_have_w6 : w6.isHave
  W9_guard_domain_b_B3 : domain_Enum_0 b_B3
  W9_guard_reveal_b_B3 : b_B3 = (w6.getHave W9_guard_have_w6).hidden_b_B3.reveal

structure ActionDag : Type where
  action0 : W0
  action1 : W1
  action2 : W2
  action3 : W3
  action4 : W4 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)
  action5 : W5 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)
  action6 : W6 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3)
  action7 : W7 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3) (UnlessQuit.have action4) (UnlessQuit.have action5) (UnlessQuit.have action6)
  action8 : W8 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3) (UnlessQuit.have action4) (UnlessQuit.have action5) (UnlessQuit.have action6)
  action9 : W9 (UnlessQuit.have action0) (UnlessQuit.have action1) (UnlessQuit.have action2) (UnlessQuit.have action3) (UnlessQuit.have action4) (UnlessQuit.have action5) (UnlessQuit.have action6)

structure EventDag : Type where
  event0 : UnlessQuit Role.Seller (W0)
  event1 : UnlessQuit Role.B1 (W1)
  event2 : UnlessQuit Role.B2 (W2)
  event3 : UnlessQuit Role.B3 (W3)
  event4 : UnlessQuit Role.B1 (W4 event0 event1 event2 event3)
  event5 : UnlessQuit Role.B2 (W5 event0 event1 event2 event3)
  event6 : UnlessQuit Role.B3 (W6 event0 event1 event2 event3)
  event7 : UnlessQuit Role.B1 (W7 event0 event1 event2 event3 event4 event5 event6)
  event8 : UnlessQuit Role.B2 (W8 event0 event1 event2 event3 event4 event5 event6)
  event9 : UnlessQuit Role.B3 (W9 event0 event1 event2 event3 event4 event5 event6)

end GameProtocol
