(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Guest | Host.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  z = 0%Z \/ z = 1%Z \/ z = 2%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : @W0)
 : Type := {
}.

Record W2 
  (w0 : @W0)
  (w1 : @W1 w0)
 : Type := {
  hidden_car_Host : Hidden Z;

  W2_guard_domain : domain_Enum_0 (reveal hidden_car_Host);
}.

Record W3 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
 : Type := {
  d_Guest : Z;

  W3_guard_domain : domain_Enum_0 d_Guest;
}.

Record W4 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
 : Type := {
  goat_Host : Z;

  W4_guard_domain : domain_Enum_0 goat_Host;
  W4_guard_logic : negb (Z.eqb goat_Host w3.(d_Guest)) = true;
}.

Record W5 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
 : Type := {
  switch_Guest : bool;

}.

Record W6 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3 w4)
 : Type := {
  car_Host : Z;

  W6_guard_domain : domain_Enum_0 car_Host;
  W6_guard_reveal : car_Host = reveal w2.(hidden_car_Host);
  W6_guard_logic : negb (Z.eqb w4.(goat_Host) car_Host) = true;
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1 action0;
  action2 : @W2 action0 action1;
  action3 : @W3 action0 action1 action2;
  action4 : @W4 action0 action1 action2 action3;
  action5 : @W5 action0 action1 action2 action3 action4;
  action6 : @W6 action0 action1 action2 action3 action4 action5;
}.

End GameProtocol.
