(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | Even | Odd.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1  : Type := {
}.

Record W2 
  (w0 : @W0)
  (w1 : @W1)
 : Type := {
  hidden_c_Odd : Hidden bool;

}.

Record W3 
  (w0 : @W0)
  (w1 : @W1)
 : Type := {
  hidden_c_Even : Hidden bool;

}.

Record W4 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1)
 : Type := {
  c_Odd : bool;

  W4_guard_reveal : c_Odd = reveal w2.(hidden_c_Odd);
}.

Record W5 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1)
 : Type := {
  c_Even : bool;

  W5_guard_reveal : c_Even = reveal w3.(hidden_c_Even);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1;
  action2 : @W2 action0 action1;
  action3 : @W3 action0 action1;
  action4 : @W4 action0 action1 action2 action3;
  action5 : @W5 action0 action1 action2 action3;
}.

End GameProtocol.
