(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | A | B.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : @W0)
 : Type := {
}.

Record W2 
  (w0 : @W0)
  (w1 : @W1 w0)
 : Type := {
  hidden_c_A : Hidden bool;

}.

Record W3 
  (w0 : @W0)
  (w1 : @W1 w0)
 : Type := {
  hidden_c_B : Hidden bool;

}.

Record W4 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1)
 : Type := {
  c_A : bool;

  W4_guard_reveal : c_A = reveal w2.(hidden_c_A);
}.

Record W5 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1)
 : Type := {
  c_B : bool;

  W5_guard_reveal : c_B = reveal w3.(hidden_c_B);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1 action0;
  action2 : @W2 action0 action1;
  action3 : @W3 action0 action1;
  action4 : @W4 action0 action1 action2 action3;
  action5 : @W5 action0 action1 action2 action3;
}.

End GameProtocol.
