(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | O | X.

(* --- Domain Constraints --- *)
Definition domain_Enum_2 (z : Z) : Prop :=
  z = 0%Z \/ z = 1%Z \/ z = 2%Z \/ z = 3%Z \/ z = 4%Z \/ z = 5%Z \/ z = 6%Z \/ z = 7%Z \/ z = 8%Z.
Definition domain_Enum_0 (z : Z) : Prop :=
  z = 0%Z \/ z = 1%Z \/ z = 4%Z.
Definition domain_Enum_1 (z : Z) : Prop :=
  z = 1%Z \/ z = 3%Z \/ z = 4%Z \/ z = 5%Z \/ z = 9%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1 
  (w0 : @W0)
 : Type := {
}.

Record W2 
  (w0 : @W0)
  (w1 : @W1 w0)
 : Type := {
  c1_X : Z;

  W2_guard_domain : domain_Enum_0 c1_X;
}.

Record W3 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
 : Type := {
  c1_O : Z;

  W3_guard_domain : domain_Enum_1 c1_O;
  W3_guard_logic : negb (Z.eqb w2.(c1_X) c1_O) = true;
}.

Record W4 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
 : Type := {
  c2_X : Z;

  W4_guard_domain : domain_Enum_2 c2_X;
  W4_guard_logic : andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) c2_X))) (negb (Z.eqb w3.(c1_O) c2_X)) = true;
}.

Record W5 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
 : Type := {
  c2_O : Z;

  W5_guard_domain : domain_Enum_2 c2_O;
  W5_guard_logic : andb (andb (andb (andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) w4.(c2_X)))) (negb (Z.eqb w2.(c1_X) c2_O))) (negb (Z.eqb w3.(c1_O) w4.(c2_X)))) (negb (Z.eqb w3.(c1_O) c2_O))) (negb (Z.eqb w4.(c2_X) c2_O)) = true;
}.

Record W6 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3 w4)
 : Type := {
  c3_X : Z;

  W6_guard_domain : domain_Enum_2 c3_X;
  W6_guard_logic : andb (andb (andb (andb (andb (andb (andb (andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) w4.(c2_X)))) (negb (Z.eqb w2.(c1_X) w5.(c2_O)))) (negb (Z.eqb w2.(c1_X) c3_X))) (negb (Z.eqb w3.(c1_O) w4.(c2_X)))) (negb (Z.eqb w3.(c1_O) w5.(c2_O)))) (negb (Z.eqb w3.(c1_O) c3_X))) (negb (Z.eqb w4.(c2_X) w5.(c2_O)))) (negb (Z.eqb w4.(c2_X) c3_X))) (negb (Z.eqb w5.(c2_O) c3_X)) = true;
}.

Record W7 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3 w4)
  (w6 : @W6 w0 w1 w2 w3 w4 w5)
 : Type := {
  c3_O : Z;

  W7_guard_domain : domain_Enum_2 c3_O;
  W7_guard_logic : andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) w4.(c2_X)))) (negb (Z.eqb w2.(c1_X) w5.(c2_O)))) (negb (Z.eqb w2.(c1_X) w6.(c3_X)))) (negb (Z.eqb w2.(c1_X) c3_O))) (negb (Z.eqb w3.(c1_O) w4.(c2_X)))) (negb (Z.eqb w3.(c1_O) w5.(c2_O)))) (negb (Z.eqb w3.(c1_O) w6.(c3_X)))) (negb (Z.eqb w3.(c1_O) c3_O))) (negb (Z.eqb w4.(c2_X) w5.(c2_O)))) (negb (Z.eqb w4.(c2_X) w6.(c3_X)))) (negb (Z.eqb w4.(c2_X) c3_O))) (negb (Z.eqb w5.(c2_O) w6.(c3_X)))) (negb (Z.eqb w5.(c2_O) c3_O))) (negb (Z.eqb w6.(c3_X) c3_O)) = true;
}.

Record W8 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3 w4)
  (w6 : @W6 w0 w1 w2 w3 w4 w5)
  (w7 : @W7 w0 w1 w2 w3 w4 w5 w6)
 : Type := {
  c4_X : Z;

  W8_guard_domain : domain_Enum_2 c4_X;
  W8_guard_logic : andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) w4.(c2_X)))) (negb (Z.eqb w2.(c1_X) w5.(c2_O)))) (negb (Z.eqb w2.(c1_X) w6.(c3_X)))) (negb (Z.eqb w2.(c1_X) w7.(c3_O)))) (negb (Z.eqb w2.(c1_X) c4_X))) (negb (Z.eqb w3.(c1_O) w4.(c2_X)))) (negb (Z.eqb w3.(c1_O) w5.(c2_O)))) (negb (Z.eqb w3.(c1_O) w6.(c3_X)))) (negb (Z.eqb w3.(c1_O) w7.(c3_O)))) (negb (Z.eqb w3.(c1_O) c4_X))) (negb (Z.eqb w4.(c2_X) w5.(c2_O)))) (negb (Z.eqb w4.(c2_X) w6.(c3_X)))) (negb (Z.eqb w4.(c2_X) w7.(c3_O)))) (negb (Z.eqb w4.(c2_X) c4_X))) (negb (Z.eqb w5.(c2_O) w6.(c3_X)))) (negb (Z.eqb w5.(c2_O) w7.(c3_O)))) (negb (Z.eqb w5.(c2_O) c4_X))) (negb (Z.eqb w6.(c3_X) w7.(c3_O)))) (negb (Z.eqb w6.(c3_X) c4_X))) (negb (Z.eqb w7.(c3_O) c4_X)) = true;
}.

Record W9 
  (w0 : @W0)
  (w1 : @W1 w0)
  (w2 : @W2 w0 w1)
  (w3 : @W3 w0 w1 w2)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3 w4)
  (w6 : @W6 w0 w1 w2 w3 w4 w5)
  (w7 : @W7 w0 w1 w2 w3 w4 w5 w6)
  (w8 : @W8 w0 w1 w2 w3 w4 w5 w6 w7)
 : Type := {
  c4_O : Z;

  W9_guard_domain : domain_Enum_2 c4_O;
  W9_guard_logic : andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (andb (negb (Z.eqb w2.(c1_X) w3.(c1_O))) (negb (Z.eqb w2.(c1_X) w4.(c2_X)))) (negb (Z.eqb w2.(c1_X) w5.(c2_O)))) (negb (Z.eqb w2.(c1_X) w6.(c3_X)))) (negb (Z.eqb w2.(c1_X) w7.(c3_O)))) (negb (Z.eqb w2.(c1_X) w8.(c4_X)))) (negb (Z.eqb w2.(c1_X) c4_O))) (negb (Z.eqb w3.(c1_O) w4.(c2_X)))) (negb (Z.eqb w3.(c1_O) w5.(c2_O)))) (negb (Z.eqb w3.(c1_O) w6.(c3_X)))) (negb (Z.eqb w3.(c1_O) w7.(c3_O)))) (negb (Z.eqb w3.(c1_O) w8.(c4_X)))) (negb (Z.eqb w3.(c1_O) c4_O))) (negb (Z.eqb w4.(c2_X) w5.(c2_O)))) (negb (Z.eqb w4.(c2_X) w6.(c3_X)))) (negb (Z.eqb w4.(c2_X) w7.(c3_O)))) (negb (Z.eqb w4.(c2_X) w8.(c4_X)))) (negb (Z.eqb w4.(c2_X) c4_O))) (negb (Z.eqb w5.(c2_O) w6.(c3_X)))) (negb (Z.eqb w5.(c2_O) w7.(c3_O)))) (negb (Z.eqb w5.(c2_O) w8.(c4_X)))) (negb (Z.eqb w5.(c2_O) c4_O))) (negb (Z.eqb w6.(c3_X) w7.(c3_O)))) (negb (Z.eqb w6.(c3_X) w8.(c4_X)))) (negb (Z.eqb w6.(c3_X) c4_O))) (negb (Z.eqb w7.(c3_O) w8.(c4_X)))) (negb (Z.eqb w7.(c3_O) c4_O))) (negb (Z.eqb w8.(c4_X) c4_O)) = true;
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1 action0;
  action2 : @W2 action0 action1;
  action3 : @W3 action0 action1 action2;
  action4 : @W4 action0 action1 action2 action3;
  action5 : @W5 action0 action1 action2 action3 action4;
  action6 : @W6 action0 action1 action2 action3 action4 action5;
  action7 : @W7 action0 action1 action2 action3 action4 action5 action6;
  action8 : @W8 action0 action1 action2 action3 action4 action5 action6 action7;
  action9 : @W9 action0 action1 action2 action3 action4 action5 action6 action7 action8;
}.

End GameProtocol.
