(* Generated by Vegas Coq Encoder - Policy: FAIR_PLAY *)
From Coq Require Import ZArith.ZArith.

Set Implicit Arguments.
Set Primitive Projections.

Definition Hidden (A : Type) : Type := { x : A & unit }.
Definition reveal {A} (h : Hidden A) : A := projT1 h.

Inductive Role : Type := | B1 | B2 | B3 | Seller.

(* --- Domain Constraints --- *)
Definition domain_Enum_0 (z : Z) : Prop :=
  (0%Z <= z)%Z /\ (z <= 2%Z)%Z.

Module GameProtocol.

Record W0  : Type := {
}.

Record W1  : Type := {
}.

Record W2  : Type := {
}.

Record W3  : Type := {
}.

Record W4 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
 : Type := {
  hidden_b_B1 : Hidden Z;

  W4_guard_domain : domain_Enum_0 (reveal hidden_b_B1);
}.

Record W5 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
 : Type := {
  hidden_b_B2 : Hidden Z;

  W5_guard_domain : domain_Enum_0 (reveal hidden_b_B2);
}.

Record W6 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
 : Type := {
  hidden_b_B3 : Hidden Z;

  W6_guard_domain : domain_Enum_0 (reveal hidden_b_B3);
}.

Record W7 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3)
  (w6 : @W6 w0 w1 w2 w3)
 : Type := {
  b_B1 : Z;

  W7_guard_domain : domain_Enum_0 b_B1;
  W7_guard_reveal : b_B1 = reveal w4.(hidden_b_B1);
}.

Record W8 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3)
  (w6 : @W6 w0 w1 w2 w3)
 : Type := {
  b_B2 : Z;

  W8_guard_domain : domain_Enum_0 b_B2;
  W8_guard_reveal : b_B2 = reveal w5.(hidden_b_B2);
}.

Record W9 
  (w0 : @W0)
  (w1 : @W1)
  (w2 : @W2)
  (w3 : @W3)
  (w4 : @W4 w0 w1 w2 w3)
  (w5 : @W5 w0 w1 w2 w3)
  (w6 : @W6 w0 w1 w2 w3)
 : Type := {
  b_B3 : Z;

  W9_guard_domain : domain_Enum_0 b_B3;
  W9_guard_reveal : b_B3 = reveal w6.(hidden_b_B3);
}.

Record ActionDag : Type := {
  action0 : @W0;
  action1 : @W1;
  action2 : @W2;
  action3 : @W3;
  action4 : @W4 action0 action1 action2 action3;
  action5 : @W5 action0 action1 action2 action3;
  action6 : @W6 action0 action1 action2 action3;
  action7 : @W7 action0 action1 action2 action3 action4 action5 action6;
  action8 : @W8 action0 action1 action2 action3 action4 action5 action6;
  action9 : @W9 action0 action1 action2 action3 action4 action5 action6;
}.

End GameProtocol.
